In [1]:
!pip install pandas scikit-learn

Requirement already satisfied: pandas in c:\users\maria\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: scikit-learn in c:\users\maria\anaconda3\lib\site-packages (1.7.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\maria\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\maria\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\maria\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\maria\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: scipy>=1.8.0 in c:\users\maria\anaconda3\lib\site-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in c:\users\maria\anaconda3\lib\site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\maria\anaconda3\lib\site-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: six>=1.5 in c:\users\maria\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [3]:
data = {
    "text": [
        "I am very happy today",
        "I love this amazing day",
        "I feel excited about my results",
        
        "I am sad and lonely",
        "I miss my friends",
        "I feel terrible today",
        
        "I am angry with you",
        "This makes me so mad",
        "I hate this situation",
        
        "I am scared of the exam",
        "I feel nervous and afraid",
        "I am worried about tomorrow"
    ],
    
    "emotion": [
        "happy",
        "happy",
        "happy",
        
        "sad",
        "sad",
        "sad",
        
        "angry",
        "angry",
        "angry",
        
        "fear",
        "fear",
        "fear"
    ]
}


df = pd.DataFrame(data)

df

                               text emotion
0             I am very happy today   happy
1           I love this amazing day   happy
2   I feel excited about my results   happy
3               I am sad and lonely     sad
4                 I miss my friends     sad
5             I feel terrible today     sad
6               I am angry with you   angry
7              This makes me so mad   angry
8             I hate this situation   angry
9           I am scared of the exam    fear
10        I feel nervous and afraid    fear
11      I am worried about tomorrow    fear

In [ ]:
X = df["text"]
y = df["emotion"]


vectorizer = TfidfVectorizer()

X = vectorizer.fit_transform(X)


model = MultinomialNB()

model.fit(X, y)

print("AI model trained ✅")

In [6]:
sentence = ["I am feeling amazing today"]

sentence_vector = vectorizer.transform(sentence)

prediction = model.predict(sentence_vector)

print("Emotion:", prediction[0])

NameError: name 'vectorizer' is not defined

In [5]:
import pandas as pd

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB

In [8]:
data = {
    "text": [
        "I am very happy today",
        "I love this amazing day",
        "I feel excited about my results",
        "I am sad and lonely",
        "I miss my friends",
        "I feel terrible today",
        "I am angry with you",
        "This makes me so mad",
        "I hate this situation",
        "I am scared of the exam",
        "I feel nervous and afraid",
        "I am worried about tomorrow"
    ],
    "emotion": [
        "happy","happy","happy",
        "sad","sad","sad",
        "angry","angry","angry",
        "fear","fear","fear"
    ]
}

df = pd.DataFrame(data)

In [9]:
X = df["text"]
y = df["emotion"]

vectorizer = TfidfVectorizer()

X_vectorized = vectorizer.fit_transform(X)

model = MultinomialNB()

model.fit(X_vectorized, y)

print("AI model trained ✅")

AI model trained ✅

In [10]:
sentence = ["I am feeling amazing today"]

sentence_vector = vectorizer.transform(sentence)

prediction = model.predict(sentence_vector)

print("Emotion:", prediction[0])

Emotion: happy

In [16]:
data = {
    "text": [
        # Happy
        "I am very happy today",
        "I love this amazing day",
        "I feel excited about my results",
        "I got a new laptop and I am excited",
        "I won a prize today",
        "I am enjoying my life",
        "This is the best day ever",
        "I am smiling and feeling great",
        "I am so proud of myself",

        # Sad
        "I am sad and lonely",
        "I miss my friends",
        "I feel terrible today",
        "I failed my exam",
        "I lost something important",
        "I feel disappointed",
        "I am crying today",
        "My heart feels broken",
        "I feel unhappy",

        # Angry
        "I am angry with you",
        "This makes me so mad",
        "I hate this situation",
        "I am frustrated",
        "Someone made me angry",
        "This is annoying",
        "I cannot accept this",

        # Fear
        "I am scared of the exam",
        "I feel nervous and afraid",
        "I am worried about tomorrow",
        "I am afraid of the dark",
        "I feel scared",
        "I am nervous about my presentation",
        "I am worried about my future"
    ],

    "emotion": [
        "happy","happy","happy","happy","happy","happy","happy","happy","happy",
        "sad","sad","sad","sad","sad","sad","sad","sad","sad",
        "angry","angry","angry","angry","angry","angry","angry",
        "fear","fear","fear","fear","fear","fear","fear"
    ]
}

df = pd.DataFrame(data)

df.head()

                                  text emotion
0                I am very happy today   happy
1              I love this amazing day   happy
2      I feel excited about my results   happy
3  I got a new laptop and I am excited   happy
4                  I won a prize today   happy

In [17]:
X = df["text"]
y = df["emotion"]

vectorizer = TfidfVectorizer()

X_vectorized = vectorizer.fit_transform(X)

model = MultinomialNB()

model.fit(X_vectorized, y)

print("Model updated ✅")

Model updated ✅

In [18]:
sentence = ["I got a new laptop today and I am excited"]

sentence_vector = vectorizer.transform(sentence)

prediction = model.predict(sentence_vector)

print("Emotion:", prediction[0])

Emotion: happy

In [21]:
def detect_emotion(sentence):
    sentence_vector = vectorizer.transform([sentence])
    prediction = model.predict(sentence_vector)
    return prediction[0]

In [22]:
detect_emotion("I passed my exam today")

np.str_('sad')

In [55]:
def detect_emotion_with_confidence(sentence):
    sentence_vector = vectorizer.transform([sentence])

    prediction = model.predict(sentence_vector)[0]

    probability = model.predict_proba(sentence_vector).max()

    confidence = round(probability * 100, 2)

    return prediction, confidence

In [56]:
detect_emotion_with_confidence("I got a new laptop and I am excited")

(np.int64(1), np.float64(76.27))

In [28]:
"I am so excited today",
"I feel wonderful",
"I am having a great day",
"I am extremely happy",
"I received great news",
"I achieved my goal",
"I am proud of myself",
"I love my new laptop",
"I am enjoying my new device",
"This makes me very happy",

('This makes me very happy',)

In [29]:
"I feel bad today",
"I am unhappy",
"I feel disappointed",
"I am having a difficult day",
"I feel broken",

('I feel broken',)

In [30]:
from sklearn.naive_bayes import MultinomialNB

In [31]:
from sklearn.linear_model import LogisticRegression

In [ ]:
model = MultinomialNB()

In [32]:
model = LogisticRegression()

In [35]:
!pip install datasets

Requirement already satisfied: datasets in c:\users\maria\anaconda3\lib\site-packages (5.0.0)
Requirement already satisfied: filelock in c:\users\maria\anaconda3\lib\site-packages (from datasets) (3.20.0)
Requirement already satisfied: numpy>=1.17 in c:\users\maria\anaconda3\lib\site-packages (from datasets) (2.3.5)
Requirement already satisfied: pyarrow>=21.0.0 in c:\users\maria\anaconda3\lib\site-packages (from datasets) (21.0.0)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in c:\users\maria\anaconda3\lib\site-packages (from datasets) (0.4.1)
Requirement already satisfied: pandas in c:\users\maria\anaconda3\lib\site-packages (from datasets) (2.3.3)
Requirement already satisfied: requests>=2.32.2 in c:\users\maria\anaconda3\lib\site-packages (from datasets) (2.32.5)
Requirement already satisfied: httpx<1.0.0 in c:\users\maria\anaconda3\lib\site-packages (from datasets) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in c:\users\maria\anaconda3\lib\site-packages (from datasets) (4.67.1)
Requirement already satisfied: xxhash in c:\users\maria\anaconda3\lib\site-packages (from datasets) (3.8.1)
Requirement already satisfied: multiprocess<0.70.20 in c:\users\maria\anaconda3\lib\site-packages (from datasets) (0.70.19)
Requirement already satisfied: fsspec<=2026.4.0,>=2023.1.0 in c:\users\maria\anaconda3\lib\site-packages (from fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (2025.10.0)
Requirement already satisfied: huggingface-hub<2.0,>=0.25.0 in c:\users\maria\anaconda3\lib\site-packages (from datasets) (1.23.0)
Requirement already satisfied: packaging in c:\users\maria\anaconda3\lib\site-packages (from datasets) (25.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\maria\anaconda3\lib\site-packages (from datasets) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in c:\users\maria\anaconda3\lib\site-packages (from fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (3.13.2)
Requirement already satisfied: anyio in c:\users\maria\anaconda3\lib\site-packages (from httpx<1.0.0->datasets) (4.10.0)
Requirement already satisfied: certifi in c:\users\maria\anaconda3\lib\site-packages (from httpx<1.0.0->datasets) (2025.11.12)
Requirement already satisfied: httpcore==1.* in c:\users\maria\anaconda3\lib\site-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in c:\users\maria\anaconda3\lib\site-packages (from httpx<1.0.0->datasets) (3.11)
Requirement already satisfied: h11>=0.16 in c:\users\maria\anaconda3\lib\site-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in c:\users\maria\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (8.4.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in c:\users\maria\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (1.5.1)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\users\maria\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (4.15.0)
Requirement already satisfied: colorama in c:\users\maria\anaconda3\lib\site-packages (from click<9.0.0,>=8.4.2->huggingface-hub<2.0,>=0.25.0->datasets) (0.4.6)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in c:\users\maria\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in c:\users\maria\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\maria\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\maria\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\maria\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in c:\users\maria\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\users\maria\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (1.22.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\maria\anaconda3\lib\site-packages (from requests>=2.32.2->datasets) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\maria\anaconda3\lib\site-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: sniffio>=1.1 in c:\users\maria\anaconda3\lib\site-packages (from anyio->httpx<1.0.0->datasets) (1.3.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\maria\anaconda3\lib\site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\maria\anaconda3\lib\site-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\maria\anaconda3\lib\site-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\maria\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)

In [37]:
from datasets import load_dataset

dataset = load_dataset("dair-ai/emotion")

dataset

DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 16000
    })
    validation: Dataset({
        features: ['text', 'label'],
        num_rows: 2000
    })
    test: Dataset({
        features: ['text', 'label'],
        num_rows: 2000
    })
})

In [38]:
train_data = dataset["train"]

texts = train_data["text"]
labels = train_data["label"]

print(texts[:5])
print(labels[:5])

['i didnt feel humiliated', 'i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake', 'im grabbing a minute to post i feel greedy wrong', 'i am ever feeling nostalgic about the fireplace i will know that it is still on the property', 'i am feeling grouchy']
[0, 0, 3, 2, 3]

In [39]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(max_features=5000)

X = vectorizer.fit_transform(texts)
y = labels

In [40]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

model.fit(X, y)

print("New AI model trained ✅")

New AI model trained ✅

In [42]:
sentence = ["I got a new laptop today and I am very excited"]

sentence_vector = vectorizer.transform(sentence)

prediction = model.predict(sentence_vector)

print(prediction)

[1]

In [43]:
from datasets import load_dataset

dataset = load_dataset("dair-ai/emotion")

dataset

DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 16000
    })
    validation: Dataset({
        features: ['text', 'label'],
        num_rows: 2000
    })
    test: Dataset({
        features: ['text', 'label'],
        num_rows: 2000
    })
})

In [44]:
train_data = dataset["train"]

print(train_data[0])

{'text': 'i didnt feel humiliated', 'label': 0}

In [45]:
id2label = dataset["train"].features["label"].names

id2label

['sadness', 'joy', 'love', 'anger', 'fear', 'surprise']

In [46]:
['sadness', 'joy', 'love', 'anger', 'fear', 'surprise']

['sadness', 'joy', 'love', 'anger', 'fear', 'surprise']

In [47]:
id2label = dataset["train"].features["label"].names

id2label

['sadness', 'joy', 'love', 'anger', 'fear', 'surprise']

In [48]:
train_data = dataset["train"]

texts = train_data["text"]
labels = train_data["label"]

print(len(texts))
print(len(labels))

16000
16000

In [49]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(max_features=5000)

X = vectorizer.fit_transform(texts)

y = labels

print(X.shape)

(16000, 5000)

In [50]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

model.fit(X, y)

print("AI training complete ✅")

AI training complete ✅

In [58]:
def detect_emotion(sentence):
    sentence_vector = vectorizer.transform([sentence])

    prediction = model.predict(sentence_vector)[0]

    confidence = model.predict_proba(sentence_vector).max()

    emotion = id2label[prediction]

    return emotion, round(confidence * 100, 2)

In [59]:
detect_emotion("I got a new laptop today and I am very excited")

('joy', np.float64(78.17))

In [60]:
detect_emotion("I failed my exam and I feel terrible")

('sadness', np.float64(77.02))

In [61]:
detect_emotion("I am afraid of tomorrow")

('fear', np.float64(85.83))

In [62]:
emotion_emoji = {
    "joy": "😊",
    "sadness": "😢",
    "anger": "😡",
    "fear": "😨",
    "love": "❤️",
    "surprise": "😲"
}


def emotion_app(sentence):
    emotion, confidence = detect_emotion(sentence)

    emoji = emotion_emoji[emotion]

    print(f"Emotion: {emoji} {emotion}")
    print(f"Confidence: {confidence}%")

In [63]:
emotion_app("I got accepted into my dream university")

Emotion: 😊 joy
Confidence: 74.15%

In [64]:
!pip install streamlit

Requirement already satisfied: streamlit in c:\users\maria\anaconda3\lib\site-packages (1.51.0)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<6,>=4.0 in c:\users\maria\anaconda3\lib\site-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in c:\users\maria\anaconda3\lib\site-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<7,>=4.0 in c:\users\maria\anaconda3\lib\site-packages (from streamlit) (5.5.1)
Requirement already satisfied: click<9,>=7.0 in c:\users\maria\anaconda3\lib\site-packages (from streamlit) (8.4.2)
Requirement already satisfied: numpy<3,>=1.23 in c:\users\maria\anaconda3\lib\site-packages (from streamlit) (2.3.5)
Requirement already satisfied: packaging<26,>=20 in c:\users\maria\anaconda3\lib\site-packages (from streamlit) (25.0)
Requirement already satisfied: pandas<3,>=1.4.0 in c:\users\maria\anaconda3\lib\site-packages (from streamlit) (2.3.3)
Requirement already satisfied: pillow<13,>=7.1.0 in c:\users\maria\anaconda3\lib\site-packages (from streamlit) (12.0.0)
Requirement already satisfied: protobuf<7,>=3.20 in c:\users\maria\anaconda3\lib\site-packages (from streamlit) (5.29.3)
Requirement already satisfied: pyarrow<22,>=7.0 in c:\users\maria\anaconda3\lib\site-packages (from streamlit) (21.0.0)
Requirement already satisfied: requests<3,>=2.27 in c:\users\maria\anaconda3\lib\site-packages (from streamlit) (2.32.5)
Requirement already satisfied: tenacity<10,>=8.1.0 in c:\users\maria\anaconda3\lib\site-packages (from streamlit) (9.1.2)
Requirement already satisfied: toml<2,>=0.10.1 in c:\users\maria\anaconda3\lib\site-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.4.0 in c:\users\maria\anaconda3\lib\site-packages (from streamlit) (4.15.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in c:\users\maria\anaconda3\lib\site-packages (from streamlit) (6.0.0)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in c:\users\maria\anaconda3\lib\site-packages (from streamlit) (3.1.45)
Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in c:\users\maria\anaconda3\lib\site-packages (from streamlit) (6.5.1)
Requirement already satisfied: jinja2 in c:\users\maria\anaconda3\lib\site-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in c:\users\maria\anaconda3\lib\site-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (4.25.0)
Requirement already satisfied: narwhals>=1.14.2 in c:\users\maria\anaconda3\lib\site-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (2.7.0)
Requirement already satisfied: colorama in c:\users\maria\anaconda3\lib\site-packages (from click<9,>=7.0->streamlit) (0.4.6)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\maria\anaconda3\lib\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: smmap<6,>=3.0.1 in c:\users\maria\anaconda3\lib\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\maria\anaconda3\lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\maria\anaconda3\lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\maria\anaconda3\lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\maria\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\maria\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\maria\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\maria\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (2025.11.12)
Requirement already satisfied: attrs>=22.2.0 in c:\users\maria\anaconda3\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\maria\anaconda3\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\maria\anaconda3\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\maria\anaconda3\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (0.28.0)
Requirement already satisfied: six>=1.5 in c:\users\maria\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas<3,>=1.4.0->streamlit) (1.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\maria\anaconda3\lib\site-packages (from jinja2->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (3.0.2)

In [66]:
import pickle

pickle.dump(model, open("emotion_model.pkl", "wb"))
pickle.dump(vectorizer, open("vectorizer.pkl", "wb"))
pickle.dump(id2label, open("labels.pkl", "wb"))

print("Model saved ✅")

Model saved ✅